---
- name: Uninstall old versions of Docker and related packages
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: yes

- name: Ensure the Docker GPG keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 'a+r'

- name: Add Docker repository to Apt sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    create: yes

- name: Update the apt package index (again)
  ansible.builtin.apt:
    update_cache: yes


- name: Install Docker Engine, CLI, and Containerd packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Verify Docker Engine installation by running hello-world
  ansible.builtin.shell: docker run hello-world
  ignore_errors: yes

- name: Enable Docker service to start on boot
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Enable containerd service to start on boot
  ansible.builtin.systemd:
    name: containerd.service
    enabled: yes
    state: started
    daemon_reload: yes